Feat/add prettier
DiceDB/playground-web pull request #11
Opened 2024-10-01 06:12 UTC by Sama-004

let me know if you want to add something else in the prettierrc

2024-10-02 15:35 UTC, lucifercr07 requested changes
@Sama-004 please resolve conflicts.

2024-10-03 05:57 UTC, Sama-004 commented
> @Sama-004 please resolve conflicts.

done

2024-10-03 06:10 UTC, lucifercr07 commented on .prettierignore
If you can add this as a Github workflow would be helpful.

2024-10-03 06:32 UTC, Sama-004 commented on .prettierignore
right now this would work for people who use prettier locally in their dev environment. And yeah it makes sense to also create a github workflow for people who are not using prettier locally. 

Do you want me to create a separate pr for adding the workflow or i should do it here itself?

2024-10-03 06:41 UTC, lucifercr07 commented on .prettierignore
Should be fine if you add in this PR, also if it can be added in `scripts` would be helpful what do you think?

2024-10-03 06:48 UTC, Sama-004 commented on .prettierignore
what i am thinking is adding prettier check in the workflow. It will check if there is any issue with the formatting. If there is then the user would need to run a script locally to fix the formatting.

The other option is to check and make changes directly via the workflow, but it would mess up the commit history so i think going with the 1st option makes sense.

2024-10-03 06:54 UTC, lucifercr07 commented on .prettierignore
Yes it's 1st one I'm talking about, `scripts` I'm stating is the one in `package.json` not any separate script.

2024-10-03 07:41 UTC, Sama-004 commented on .prettierignore
yeah on it 👍

2024-10-03 13:48 UTC, Sama-004 commented
@lucifercr07  I've added the script and workflow. You can check [this](https://github.com/Sama-004/playground-web/pull/3) to see how it works.

But there is a problem. Right now the error message is being displayed on the workflow console. I also want to display a the echo directly on the status page but idk how to do it. let me know if you have any suggestions. I think a bot can also do this but there should be a way to show the message on the workflow status right? 
![image](https://github.com/user-attachments/assets/70a92659-5e7c-4a13-8a9a-2d8406ab08fb)

2024-10-03 18:39 UTC, lucifercr07 approved these changes

2024-10-03 18:44 UTC, merged