Feature/add tooltip component
DiceDB/playground-web pull request #59
Opened 2024-10-07 14:08 UTC by RishabhC-137

This pull request resolves several issues mentioned in[Issue #35](https://github.com/DiceDB/playground-web/issues/35):

- Styling Fixes: Aligned styles for “Cleanup in:” and “Commands left:”; updated to “Commands left:” and added tooltips.
- File Cleanup: Removed mockData.json file.
- Variable Update: Changed “blacklist” to “blocklist” in variable names.

2024-10-08 04:48 UTC, RishabhC-137 commented
@lucifercr07 can you review this pr?

2024-10-08 12:11 UTC, lucifercr07 commented
@RishabhC-137 please resolve conflicts.

2024-10-09 09:07 UTC, RishabhC-137 commented
@lucifercr07 can you check

2024-10-09 09:09 UTC, lucifercr07 requested changes
@RishabhC-137 can you please add some screenshots for the changes?

2024-10-09 09:09 UTC, lucifercr07 commented on next-env.d.ts
> +/// <reference types="next" />
Why's this file required?

2024-10-09 09:28 UTC, RishabhC-137 commented
@lucifercr07 Hi, I added tooltip (i) icons next to both phrases to provide context:
- "Cleanup in:": "Time remaining for cleanup tasks."
- "Commands left:": "Number of commands you can still execute."

https://github.com/user-attachments/assets/73135864-373b-426e-83bf-155f487b18f0

![image](https://github.com/user-attachments/assets/67f188ba-9013-44b0-abc0-84785ece7759)

2024-10-09 12:19 UTC, RishabhC-137 commented
@lucifercr07 can you check

2024-10-09 13:03 UTC, merged